---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

eigenlayer:
  eigenda:
    source_url: ghcr.io/layr-labs/eigenda/opr-node
    cli:
      source_url: https://github.com/Layr-Labs/eigenlayer-cli/releases/download
    srs:
      source_url: https://srs-mainnet.s3.amazonaws.com/kzg
    ports:
      dispersal_port: 32005
      retrieval_port: 32004
      metrics_port: 9092
      node_api_port: 9091
  eoracle:
    source_url: eoracle/data-validator
    cli:
      source_url: https://github.com/Eoracle/Eoracle-operator-cli/releases/download
    ports:
      prometheus_port: 10004
      health_port: 10003
  omni:
    halovisor:
      source_url: omniops/halovisor
    geth:
      source_url: ethereum/client-go
    cli:
      source_url: https://github.com/omni-network/omni/releases/download
