---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

eigenlayer:
  eigenda:
    source_url: ghcr.io/layr-labs/eigenda/opr-node
    cli:
      source_url: https://github.com/Layr-Labs/eigenlayer-cli/releases/download
    ports:
      dispersal_port: 32005
      v2_dispersal_port: 32006
      retrieval_port: 32004
      v2_retrieval_port: 32007
      metrics_port: 9092
      node_api_port: 9091
