---
- name: Include the ufw rules vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ eigenda_ufw_rules }}"

- name: Include user creation task for eigen
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ eigenda_home_dir }}"
    directories: "{{ eigenda_directories }}"
    log_file_path: "{{ eigenda_log_file_path }}"

- name: Include download srs task
  ansible.builtin.include_tasks: download_srs.yml
  when: fetch_srs | default(false) | bool

- name: Include install_binary task
  ansible.builtin.include_tasks: install_binary/main.yml

- name: Copy eigenda env file
  ansible.builtin.template:
    src: "{{ env }}/general.env.j2"
    dest: "{{ eigenda_environment_general_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch bls key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ eigenda_bls_key_file_name }}"
        secret_destination_path: "{{ eigenda_bls_key_path }}"
        secret_type: json

    - name: Fetch ecdsa key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ eigenda_ecdsa_key_file_name }}"
        secret_destination_path: "{{ eigenda_ecdsa_key_path }}"
        secret_type: json
    
    - name: Fetch secrets environment file and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ eigenda_environment_secret_file_name }}"
        secret_destination_path: "{{ eigenda_environment_secret_file_path }}"
        secret_type: environment

- name: Copy eigenDA systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
