---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    eigenlayer:
      hosts:
        ts.eigenda.eigen.mainnet.encapsulate.xyz:
          type: eigenda
        eoracle.eigen.mainnet.encapsulate.xyz:
          type: eoracle
