---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    eigenlayer:
      hosts:
        validator.eigen.mainnet.encapsulate.xyz:
          type: validator
        fullnode.eigen.mainnet.encapsulate.xyz:
          type: fullnode
