---
- name: Create Eoracle Docker container and copy binary
  vars:
    container_name: eoracle_node
  block:
    - name: Create temporary Eoracle Docker container for binary extraction
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ eigenlayer.eoracle.source_url }}:{{ eigenlayer.eoracle.version }}"
        state: present
        recreate: true

    - name: Copy Eoracle binary
      ansible.builtin.shell: >
        docker cp {{ container_name }}:/usr/local/bin/data-validator {{ eoracle_bin_dir }}/{{ service_identifier }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"

    - name: Ensure Eoracle binary has the correct permissions
      ansible.builtin.file:
        path: "{{ eoracle_bin_dir }}/{{ service_identifier }}"
        owner: root
        group: root
        mode: "0755"
      notify:
        - Restart service

  always:
    - name: Remove Eoracle container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
