---
- name: Create a tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive the binary
  vars:
    suffix_url: "v{{ eigenlayer.eigenda.cli.version }}/{{ eigenda_cli_default_binary_name }}-cli_{{ eigenlayer.eigenda.cli.version }}_{{ ansible_system | lower }}_{{
      system_architecture }}.tar.gz"
  ansible.builtin.unarchive:
    src: "{{ eigenlayer.eigenda.cli.source_url }}/{{ suffix_url }}"
    dest: "{{ tmp_dir }}/{{ project }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/{{ eigenda_cli_default_binary_name }}"
    dest: "{{ eigenda_bin_dir }}/{{ eigenda_cli_default_binary_name }}-cli"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: absent
