---
- name: Create EigenDA Docker container and copy binary
  vars:
    container_name: eigenda_node
  block:
    - name: Create temporary EigenDA Docker container for binary extraction
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ eigenlayer.eigenda.source_url }}:{{ eigenlayer.eigenda.version }}"
        state: present
        recreate: true

    - name: Copy EigenDA binary
      ansible.builtin.shell: >
        docker cp {{ container_name }}:/usr/local/bin/node {{ eigenda_bin_dir }}/{{ service_identifier }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"

    - name: Ensure EigenDA binary has the correct permissions
      ansible.builtin.file:
        path: "{{ eigenda_bin_dir }}/{{ service_identifier }}"
        owner: root
        group: root
        mode: "0755"
      notify:
        - Restart service

  always:
    - name: Remove EigenDA container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
