---
# maintains file name, binary names, and anything which is not a directory or path

# key
eoracle_bls_key_file_name: wallet_bls_key.json
eoracle_ecdsa_key_file_name: wallet_ecdsa_key.json

# binary names
eoracle_cli_default_binary_name: Eoracle-operator-cli

# Environment file names
eoracle_environment_general_file_name: "{{ service_identifier }}.env"
eoracle_environment_secret_file_name: "{{ service_identifier }}.secret.env"
