---
eoracle_ufw_rules:
    - port: "{{ eigenlayer[type].ports.data_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: data_port

    - port: "{{ eigenlayer[type].ports.health_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: health_port

    - port: "{{ eigenlayer[type].ports.prometheus_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: prometheus_port
