---
- name: Download srs g1.point
  ansible.builtin.get_url:
    url: "{{ vars[project][type].srs.source_url }}/{{ node_g1_point_file_name }}"
    dest: "{{ node_g1_point_file_path }}"
    owner: "{{ service_identifier }}"
    group: root
    mode: "0644"

- name: Download srs g2.point.powerOf2
  ansible.builtin.get_url:
    url: "{{ vars[project][type].srs.source_url }}/{{ node_g2_point_file_name }}"
    dest: "{{ node_g2_point_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
